create table if not exists public.lesson_progress (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    module_id text not null,
    lesson_id text not null,
    status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
    progress_percentage integer not null default 0 check (progress_percentage >= 0 and progress_percentage <= 100),
    last_accessed timestamptz not null default now(),
    completed_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint lesson_progress_user_module_lesson_key unique (user_id, module_id, lesson_id)
);

create index if not exists lesson_progress_user_module_idx on public.lesson_progress (user_id, module_id);
create index if not exists lesson_progress_module_lesson_idx on public.lesson_progress (module_id, lesson_id);

alter table public.lesson_progress enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lesson_progress'
          and policyname = 'Users can view their lesson progress'
    ) then
        create policy "Users can view their lesson progress"
            on public.lesson_progress
            for select
            to authenticated
            using (auth.uid() = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lesson_progress'
          and policyname = 'Users can insert their lesson progress'
    ) then
        create policy "Users can insert their lesson progress"
            on public.lesson_progress
            for insert
            to authenticated
            with check (auth.uid() = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lesson_progress'
          and policyname = 'Users can update their lesson progress'
    ) then
        create policy "Users can update their lesson progress"
            on public.lesson_progress
            for update
            to authenticated
            using (auth.uid() = user_id)
            with check (auth.uid() = user_id);
    end if;
end $$;

create or replace function public.set_lesson_progress_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_lesson_progress_updated_at on public.lesson_progress;

create trigger set_lesson_progress_updated_at
    before update on public.lesson_progress
    for each row
    execute function public.set_lesson_progress_updated_at();